export const language=typeof document!=='undefined'&&document.documentElement.lang.startsWith('pt')?'pt':'en';
export const locale=language==='pt'?'pt-BR':'en-GB';
export const translations={
  'The current-distance ranking runs from smallest to largest absolute difference divided by the published margin of error. It also displays the signed percentage-point gap and the excess outside the margin. Missing margins or incompatible benchmarks are not ranked. This descriptive ratio is not a z-score or significance test: the benchmark is uncertain, and shared poll inputs can induce dependence. Historical errors remain a separate, largest-first ranking. Distance is disagreement, not proof that an institute is wrong. This comparison is not currently calculated: a validated corrected benchmark does not yet exist.':'O ranking de distância atual será ordenado da menor à maior diferença absoluta dividida pela margem de erro publicada. Também mostrará a diferença com sinal e o excedente fora da margem. Registros sem margem ou referência compatível não serão classificados. Essa razão descritiva não é um escore z nem teste de significância: a referência é incerta e pode compartilhar pesquisas de entrada. Erros históricos terão um ranking separado, do maior para o menor. Distância é divergência, não prova de erro do instituto. Esta comparação ainda não é calculada: não existe uma referência corrigida validada.',
  'Expected vote share and probability of victory are distinct outputs. The landing page currently shows selected published polls, not an election-day forecast or a projected winner. Raw vote shares are not rescaled to valid votes.':'Percentual esperado de votos e probabilidade de vitória são resultados distintos. A página inicial mostra pesquisas publicadas selecionadas, não uma previsão para a eleição ou um vencedor projetado. Percentuais brutos não são convertidos em votos válidos.',
  'Final intervals must include relevant sampling, non-sampling, demographic, turnout and future-change uncertainty. Current whiskers use the source’s published survey-wide margin, not a candidate-specific interval. Confidence levels are shown only where transcribed; no interval for Flávio minus Lula is inferred without covariance information.':'Os intervalos finais deverão incluir incertezas amostrais, não amostrais, demográficas, de comparecimento e de mudanças futuras. As hastes atuais usam a margem geral publicada pela fonte, não um intervalo específico por candidato. Níveis de confiança aparecem apenas quando transcritos; nenhum intervalo para Flávio menos Lula é inferido sem informação de covariância.',
  'LOCAL PREVIEW · Published raw polls · No corrections or forecasts · Fixed market snapshots':'PRÉVIA LOCAL · Pesquisas brutas publicadas · Sem correções ou previsões · Mercados em arquivos fixos',
  'LOCAL PREVIEW · Published raw polls · Datafolha demographic research estimate · No residual effects or forecast':'PRÉVIA LOCAL · Pesquisas brutas publicadas · Estimativa demográfica de pesquisa Datafolha · Sem efeitos residuais ou previsão',
  'Brazil’s presidential race, examined. Demographic research estimates are separated from residual institute effects and forecasts.':'A disputa presidencial brasileira em análise. Estimativas demográficas de pesquisa permanecem separadas de efeitos residuais dos institutos e previsões.',
  'Research edition · Published polling records · Archived market data':'Edição de pesquisa · Registros de pesquisas publicados · Mercados históricos',
  'Raw-data edition · Published polling records · Archived market data':'Edição de dados brutos · Pesquisas publicadas · Mercados históricos',
  'This version displays published raw polls and fixed market snapshots. No PNAD correction, house-effect adjustment, forecast, win probability or institute score is being calculated.':'Esta versão exibe pesquisas brutas publicadas e arquivos fixos de mercados. Não há cálculo de correção por PNAD, ajuste de viés, previsão, probabilidade de vitória ou nota de instituto.',
  'The charts show individual raw observations at their fieldwork midpoints, not fitted trend lines. First-round coverage is partial and candidate lists vary. No house-effect model, weighting scheme or statistical smoothing has been implemented.':'Os gráficos mostram observações brutas individuais na data média do campo, não tendências ajustadas. A cobertura do primeiro turno é parcial e as listas de candidatos variam. Não há modelo de viés, ponderação ou suavização estatística.',
  'This comparison is not currently calculated: a validated corrected benchmark does not yet exist.':'Esta comparação ainda não é calculada: não existe uma referência corrigida validada.',
  'The landing page currently shows selected published polls, not an election-day forecast or a projected winner. Raw vote shares are not rescaled to valid votes.':'A página inicial mostra pesquisas publicadas selecionadas, não uma previsão para a eleição ou um vencedor projetado. Percentuais brutos não são convertidos em votos válidos.',
  'Current whiskers use the source’s published survey-wide margin, not a candidate-specific interval. Confidence levels are shown only where transcribed; no interval for Flávio minus Lula is inferred without covariance information.':'As hastes atuais usam a margem geral publicada pela fonte, não um intervalo específico por candidato. Níveis de confiança aparecem apenas quando transcritos; nenhum intervalo para Flávio menos Lula é inferido sem informação de covariância.',
  'Inspect the raw polling database':'Consultar a base de pesquisas brutas',
  'Observation times may differ by series. Move across the chart to inspect · focus the chart and use ← / →':'Os horários podem variar entre as séries. Passe o ponteiro pelo gráfico · selecione o gráfico e use ← / →',
  'All institutes · synthetic series':'Todos os institutos · séries sintéticas',
  'The vote-share chart shows percentages; the lead chart shows Flávio minus Lula. Positive differences favour Flávio; negative differences favour Lula.':'O gráfico de votos mostra percentuais; o gráfico de diferença mostra Flávio menos Lula. Diferenças positivas favorecem Flávio; negativas favorecem Lula.',
  'Predict victory':'Previsão de vitória','First round':'Primeiro turno','Second round':'Segundo turno','Bet markets':'Mercados de apostas','Adjusted results':'Resultados ajustados','Offenders':'Erros dos institutos','Methodology':'Metodologia','Database':'Base de dados',
  'Language':'Idioma','On this page':'Nesta página','Skip to content':'Ir para o conteúdo','Main navigation':'Navegação principal','The Machine Observer home':'Página inicial do The Machine Observer',
  'BRAZIL · 2026':'BRASIL · 2026','Presidential election observatory':'Observatório da eleição presidencial','Evidence before certainty.':'Evidências antes da certeza.','Independent views of the race':'Uma visão independente da disputa',
  'LOCAL DESIGN PROTOTYPE · Polling & forecast figures are illustrative. Markets use an archived snapshot.':'PROTÓTIPO LOCAL · Pesquisas e previsões são ilustrativas. Mercados usam um arquivo histórico.',
  'Illustrative data':'Dados ilustrativos','Archived market data':'Dados históricos de mercados','Fictional scorecards':'Avaliações fictícias','Proposed methodology':'Metodologia proposta','Design edition · 19 September 2026':'Edição de design · 19 de setembro de 2026',
  'Brazil’s presidential race, examined. A local visual prototype: no forecast model or institute assessment is operating here.':'A disputa presidencial brasileira em análise. Protótipo visual local: não há modelo de previsão ou avaliação real de institutos em operação.',
  'How to read the numbers':'Como interpretar os números','Explore the evidence':'Explore as evidências','Prototype v0.1 · Mock polling data · Archived market data':'Protótipo v0.1 · Pesquisas fictícias · Mercados históricos','Not deployed · No production update routines connected':'Não publicado · Sem conexão com rotinas de produção',
  'The expected second-round result.':'O resultado esperado do segundo turno.',
  'Lula × Flávio Bolsonaro. Expected election-day vote shares, with uncertainty—not a first-round forecast.':'Lula × Flávio Bolsonaro. Percentuais esperados no dia da eleição, com incerteza — não uma previsão do primeiro turno.',
  'Expected second-round valid votes':'Votos válidos esperados · segundo turno','Projected winner: Lula':'Vencedor projetado: Lula','· mock result':'· resultado fictício','Projected winner · mock':'Vencedor projetado · fictício',
  '51.9% vs 48.1% of valid votes. Both intervals cross 50%; the outcome remains uncertain.':'51,9% contra 48,1% dos votos válidos. Ambos os intervalos cruzam 50%; o resultado permanece incerto.',
  '95% interval':'Intervalo de 95%','Semicircle: 100% of valid votes. Top marker: 50%.':'Semicírculo: 100% dos votos válidos. Marca superior: 50%.',
  'The outer bracket marks the illustrative 95% range for the shared boundary between candidates. Each candidate’s interval is also written below the arc. These are complementary vote shares, not independent ranges or win probabilities.':'O arco externo marca o intervalo ilustrativo de 95% para a divisão entre os candidatos. O intervalo de cada candidato também aparece abaixo do arco. São parcelas complementares dos votos, não intervalos independentes nem probabilidades de vitória.',
  'All values are synthetic. Production will use validated election-day predictive intervals.':'Todos os valores são sintéticos. A versão final usará intervalos preditivos validados para o dia da eleição.',
  'Second round · election-day forecast fixture · valid votes · not a current-poll estimate':'Segundo turno · projeção fictícia para a eleição · votos válidos · não é a estimativa atual de pesquisas',
  'Candidate':'Candidato','Expected vote':'Votos esperados','Reading':'Interpretação','Projected winner at the expected value':'Vencedor projetado pelo valor esperado','Trailing at the expected value':'Atrás no valor esperado',
  'A projected winner, not a certain winner.':'Um vencedor projetado, não uma vitória certa.',
  'Vote share and probability of winning are different quantities. These are mock vote-share estimates; no numerical win probability is implied. The two candidates’ outcomes are complementary, not independent.':'Percentual de votos e probabilidade de vitória são medidas diferentes. Estes percentuais são fictícios e não implicam uma probabilidade numérica de vitória. Os resultados dos dois candidatos são complementares, não independentes.',
  'Explore the runoff':'Explore o segundo turno','How the forecast will work':'Como funcionará a previsão','Expected result':'Resultado esperado','Vote shares & intervals':'Percentuais e intervalos','Reading the forecast':'Como ler a previsão',
  'The leading runoff.':'O confronto entre os líderes.','How the first round is taking shape.':'A evolução do primeiro turno.',
  'Only the two leading first-round candidates. Their head-to-head trend, with the uncertainty kept in view.':'Apenas os dois líderes do primeiro turno. A evolução do confronto direto, com a incerteza sempre visível.',
  'Follow the expected vote share of each candidate over time. Inspect the trend without losing sight of the underlying uncertainty.':'Acompanhe os percentuais esperados de cada candidato ao longo do tempo, sem perder de vista a incerteza.',
  'Trend period':'Período da série','3 months':'3 meses','6 months':'6 meses','All':'Todo o período','Show illustrative uncertainty':'Mostrar incerteza ilustrativa','The leading candidates':'Os candidatos líderes','Leading candidates':'Candidatos líderes','The remaining candidates':'Os demais candidatos','Other candidates':'Outros candidatos','Candidate C':'Candidato C','Candidate D':'Candidato D','Others':'Outros',
  'The distance between the leaders':'A diferença entre os líderes','Flávio minus Lula':'Flávio menos Lula',
  'The left chart shows vote shares; the right shows Flávio minus Lula. Positive differences favour Flávio; negative differences favour Lula.':'O primeiro gráfico mostra os votos; o segundo, Flávio menos Lula. Valores positivos favorecem Flávio; negativos favorecem Lula.',
  'Both panels use the same dates but different vertical scales. Compare percentages—not the visual height of lines across panels.':'Os dois gráficos usam as mesmas datas, mas escalas verticais diferentes. Compare os percentuais, não a altura visual das linhas.',
  'Source: synthetic design fixtures. Shaded bands are illustrative ranges, not calibrated intervals.':'Fonte: dados sintéticos de demonstração. As faixas sombreadas são ilustrativas, não intervalos calibrados.',
  'Download CSV':'Baixar CSV','View individual polls':'Ver pesquisas individuais','Inspect chart values':'Consultar valores do gráfico',
  'One pairing, a clear comparison.':'Um confronto, uma comparação clara.','A trend is more useful than a headline.':'Uma tendência informa mais que uma manchete.',
  'This view is deliberately limited to the two first-round leaders. Candidate selection and the eventual model will be driven by the verified data, not by this prototype.':'Esta visão se limita aos dois líderes do primeiro turno. A seleção dos candidatos e o modelo final dependerão de dados verificados, não deste protótipo.',
  'The final product will distinguish published polls from the estimated trend. These lines currently connect synthetic values and contain no forecasting model.':'A versão final distinguirá pesquisas publicadas da tendência estimada. Estas linhas conectam valores sintéticos e não representam um modelo de previsão.',
  'Uncertainty belongs in the picture.':'A incerteza faz parte da análise.',
  'The shaded range demonstrates how uncertainty could be shown. Its width is a visual placeholder; it must not be interpreted as a confidence or prediction interval.':'A faixa sombreada demonstra como apresentar incerteza. Sua largura é apenas ilustrativa e não deve ser interpretada como um intervalo de confiança ou de previsão.',
  'Institute':'Instituto','All institutes':'Todos os institutos','Period & institute':'Período e instituto','Chart values':'Valores do gráfico','How to read the trends':'Como ler as tendências','No series selected':'Nenhuma série selecionada','Select a candidate above to show the chart.':'Selecione um candidato acima para mostrar o gráfico.',
  'Move across the chart to inspect · focus the chart and use ← / →':'Passe o ponteiro pelo gráfico · selecione o gráfico e use ← / →','Observation times may differ by series.':'Os horários podem variar entre as séries.','50% reference':'Referência de 50%',
  'What the markets are pricing.':'O que os mercados estão precificando.',
  'Two markets. Two independent views of the election. Contract prices are not vote shares, and neither is our forecast.':'Dois mercados, duas visões independentes da eleição. Preços de contratos não são percentuais de votos nem a nossa previsão.',
  'Synchronized market data':'Dados sincronizados dos mercados','Loading market snapshots…':'Carregando arquivos dos mercados…',
  'These are “Yes” contract prices, multiplied by 100. Each market has its own settlement rules, liquidity and candidate selection. The displayed series need not add up to 100%.':'São preços de contratos “Sim”, multiplicados por 100. Cada mercado tem regras de liquidação, liquidez e candidatos próprios. As séries apresentadas não precisam somar 100%.',
  'Updates remain independent.':'As atualizações permanecem independentes.','Each market file loads separately with cache bypass. One unavailable provider cannot suppress the other chart. Missing observations remain missing, and long gaps break the line.':'Cada arquivo de mercado é carregado separadamente, sem usar cache. A indisponibilidade de um provedor não impede o outro gráfico. Observações ausentes continuam ausentes e lacunas longas interrompem a linha.',
  'Presidential election winner · synchronized contract prices':'Vencedor da eleição presidencial · preços sincronizados dos contratos','Starting month':'Mês inicial','Source: Kalshi synchronized snapshot.':'Fonte: arquivo sincronizado da Kalshi.','Source: Polymarket synchronized snapshot.':'Fonte: arquivo sincronizado do Polymarket.',
  'Loading the archived market snapshots…':'Carregando os arquivos históricos dos mercados…','Read prices, not predictions of votes.':'Leia preços, não previsões de votos.',
  'These are archived “Yes” contract prices, multiplied by 100. Each market has its own settlement rules, liquidity and candidate selection. The displayed series need not add up to 100%.':'São preços históricos de contratos “Sim”, multiplicados por 100. Cada mercado tem regras de liquidação, liquidez e candidatos próprios. As séries não precisam somar 100%.',
  'The snapshot is deliberately fixed.':'O arquivo histórico é intencionalmente fixo.',
  'This local prototype uses the same JSON snapshots inspected on the existing site. No live market requests or update jobs are connected. Missing observations are left missing; long gaps break the line.':'Este protótipo local usa os mesmos arquivos JSON verificados no site existente. Não há consultas ao vivo ou rotinas de atualização conectadas. Observações ausentes não são preenchidas; lacunas longas interrompem a linha.',
  'Presidential election winner · archived contract prices':'Vencedor da eleição presidencial · preços históricos de contratos','Open market':'Abrir mercado','Inspect prices and observation times':'Consultar preços e horários das observações','No observation in this period':'Nenhuma observação neste período','Reading market prices':'Como ler os preços','1D':'1 dia','1W':'1 semana','1M':'1 mês','ALL':'Tudo',
  'A record of getting it wrong.':'O histórico dos erros.',
  'Compare historical polling errors, then inspect the evidence behind each institute. A ranking should invite scrutiny—not replace it.':'Compare os erros históricos das pesquisas e consulte as evidências de cada instituto. Um ranking deve estimular a análise, não substituí-la.',
  'Historical window':'Período histórico','All elections':'Todas as eleições','All institute names and scores below are fictional.':'Todos os nomes de institutos e indicadores abaixo são fictícios.','Largest historical errors':'Maiores erros históricos','Mean absolute error · p.p.':'Erro absoluto médio · p.p.','Select an institute to inspect its scorecard. Higher error is worse.':'Selecione um instituto para consultar sua avaliação. Quanto maior o erro, pior.',
  'Illustrative scorecard':'Avaliação ilustrativa','Historical mean absolute error':'Erro absoluto médio histórico','Signed mean error':'Erro médio com sinal','Intervals covering the result':'Intervalos que contêm o resultado','Polls in comparison':'Pesquisas comparadas',
  'This is a fictional institute and a design-only grade. The final scorecard will show matched election horizons, sample coverage, uncertainty and linked source records. It will not infer quality from a single miss.':'Este instituto é fictício e sua nota serve apenas à demonstração visual. A avaliação final apresentará horizontes eleitorais comparáveis, cobertura, incerteza e fontes. Um único erro não determinará a qualidade.',
  'Read the evaluation framework':'Leia os critérios de avaliação','Distance from the Observer estimate':'Distância da estimativa do Observer',
  'Latest raw second-round poll versus our PNAD + bias-corrected estimate at that poll’s publication date. Before any election-day projection.':'Última pesquisa bruta de segundo turno versus nossa estimativa corrigida por PNAD e viés na data de publicação da pesquisa. Antes de qualquer projeção para a eleição.',
  'Least to greatest distance, adjusted for the published margin of error: |raw poll − corrected Observer estimate| ÷ margin of error. A value of 1× means one published margin away. All figures and institute names are synthetic.':'Da menor à maior distância, ajustada pela margem publicada: |pesquisa bruta − estimativa corrigida do Observer| ÷ margem de erro. O valor 1× equivale a uma margem publicada de distância. Todos os números e institutos são fictícios.',
  'Matched scenario: Lula × Flávio, total respondents on both sides. A different dated benchmark is used for each latest poll. No Monte Carlo projection. This descriptive distance is not a significance test: the Observer estimate also has uncertainty and may share poll inputs.':'Cenário comparável: Lula × Flávio, total de entrevistados dos dois lados. Cada última pesquisa usa a referência da mesma data. Sem projeção de Monte Carlo. Essa distância descritiva não é um teste de significância: a estimativa do Observer também é incerta e pode compartilhar pesquisas como insumos.',
  'How institutes will be evaluated':'Como os institutos serão avaliados','Current distance · smallest first · total respondents · benchmark version MOCK-current-v1':'Distância atual · menor primeiro · total de entrevistados · referência MOCK-current-v1',
  'Order / institute':'Ordem / instituto','Latest poll / fieldwork':'Última pesquisa / campo','Raw poll ± MoE':'Pesquisa bruta ± margem','Corrected Observer':'Observer corrigido','Signed gap':'Diferença com sinal','Distance / MoE':'Distância / margem','Beyond MoE':'Além da margem','Unavailable':'Indisponível','Not ranked':'Sem classificação','Missing comparable input':'Sem insumo comparável','Within published margin':'Dentro da margem publicada','Beyond published margin':'Além da margem publicada',
  'Signed gap = raw poll minus corrected Observer. “Beyond MoE” is the portion of the absolute gap outside the published margin, not proof of bias. Raw values are taken directly from each institute’s latest record in the':'Diferença com sinal = pesquisa bruta menos Observer corrigido. “Além da margem” é a parcela da diferença absoluta que excede a margem publicada, não uma prova de viés. Os valores brutos vêm do registro mais recente de cada instituto na',
  'second-round database':'base do segundo turno','Historical errors':'Erros históricos','Institute scorecard':'Avaliação do instituto','Current poll distance':'Distância da pesquisa atual',
  'The evidence, row by row.':'As evidências, registro a registro.',
  'Inspect individual polls, their fieldwork and their reported results. The records below are synthetic examples of the future database.':'Consulte pesquisas individuais, datas de campo e resultados divulgados. Os registros abaixo são exemplos sintéticos da futura base.',
  'First-round polls':'Pesquisas de primeiro turno','Second-round polls':'Pesquisas de segundo turno','Poll round':'Turno da pesquisa','Search polls':'Buscar pesquisas','Institute or record ID…':'Instituto ou código do registro…','Order':'Ordenação','Newest first':'Mais recentes primeiro','Oldest first':'Mais antigas primeiro','Reset filters':'Limpar filtros',
  'Published percentages stay intact.':'Os percentuais publicados são preservados.',
  'Individual records show reported values on their original denominator. Blank, null and undecided responses are not silently redistributed. The charted trend will be a separate, versioned output.':'Os registros mostram os valores publicados com sua base percentual original. Brancos, nulos e indecisos não são redistribuídos silenciosamente. A tendência será um resultado separado e versionado.',
  'A traceable record for every poll.':'Um registro rastreável para cada pesquisa.',
  'The production database will link the source report, TSE registration and any corrections. These demo IDs do not refer to real registrations.':'A base final terá links para o relatório original, registro no TSE e eventuais correções. Os códigos de demonstração não correspondem a registros reais.',
  'No polls match these filters.':'Nenhuma pesquisa corresponde aos filtros.','Try a different institute or reset the filters.':'Escolha outro instituto ou limpe os filtros.','Institute / publication':'Instituto / publicação','Fieldwork':'Campo','Other responses':'Outras respostas','Other / undecided':'Outros / indecisos','Sample':'Amostra','Record':'Registro','Synthetic record':'Registro sintético','Close':'Fechar','Close record details':'Fechar detalhes do registro','Publication':'Publicação','Round':'Turno','Method':'Método','Published margin (mock)':'Margem publicada (fictícia)','In person':'Presencial','Telephone':'Telefone','Online panel':'Painel on-line',
  'No real poll report or TSE registration is attached to this design fixture. Production records will preserve the source URL, archived report, demographic disclosures and correction history.':'Nenhum relatório real ou registro no TSE está associado a este exemplo. Os registros finais preservarão o endereço da fonte, relatório arquivado, informações demográficas e histórico de correções.',
  'Choose a round':'Escolha o turno','Search & institute':'Busca e instituto','Individual polls':'Pesquisas individuais','About the records':'Sobre os registros',
  'Show the work.':'Transparência sobre o método.',
  'A clear route from a published poll to an estimate—with the assumptions, limits and evidence left visible.':'Da pesquisa publicada à estimativa: um caminho claro, com hipóteses, limites e evidências visíveis.',
  'What each number means':'O significado de cada número','Collecting the evidence':'Coleta das evidências','Making polls comparable':'Comparabilidade das pesquisas','Demographic correction':'Correção demográfica','Learning from past errors':'Aprendizado com erros passados','From polls to a forecast':'Das pesquisas à previsão','Showing uncertainty':'Apresentação da incerteza','Keeping markets separate':'Mercados separados','A reproducible record':'Um registro reproduzível',
  'This is the proposed framework, not an operating model.':'Este é o método proposto, não um modelo em operação.',
  'This version tests the website’s design. Forecasts, polling trends, uncertainty bands and institute scores are illustrative. The market pages use existing archived snapshots.':'Esta versão testa o design do site. Previsões, tendências, faixas de incerteza e avaliações são ilustrativas. Os mercados usam arquivos históricos existentes.',
  'Published poll':'Pesquisa publicada','What respondents said in one survey, using that survey’s own denominator.':'O que os entrevistados responderam em uma pesquisa, usando a base percentual daquela pesquisa.',
  'Current estimate':'Estimativa atual','A model’s estimate of opinion now, without projecting to election day.':'A estimativa da opinião atual, sem projeção até o dia da eleição.',
  'Forecast':'Previsão','An election-day estimate, with additional uncertainty about what may change.':'Uma estimativa para o dia da eleição, com incerteza adicional sobre mudanças futuras.',
  'Market price':'Preço de mercado','The price of a contract with its own outcome and settlement rules. Never a vote share.':'Preço de um contrato com resultado e regras de liquidação próprios. Nunca um percentual de votos.',
  'Each poll will have a source report, publication date, fieldwork dates, institute identity, sample, interview method, geographic scope and election scenario. Where applicable, the record will link to its':'Cada pesquisa terá relatório original, data de publicação, datas de campo, instituto, amostra, método de entrevista, abrangência geográfica e cenário eleitoral. Quando aplicável, haverá link para seu',
  'TSE registration':'registro no TSE',
  'Registration is evidence that a survey was registered—not proof that a result was published or independently validated. Pending registrations remain separate until the relevant result is found and checked.':'O registro comprova que uma pesquisa foi registrada, não que seu resultado foi publicado ou validado de forma independente. Registros pendentes ficam separados até localizar e verificar o resultado.',
  'Original files and retrieval dates will be preserved. Duplicate releases, sponsored institute-name variants and corrections will be linked to the same canonical record rather than counted as new polls.':'Arquivos originais e datas de coleta serão preservados. Divulgações duplicadas, variações de nomes e correções serão vinculadas ao mesmo registro, sem contar como novas pesquisas.',
  'First-round and second-round scenarios remain separate. So do total-respondent percentages and valid-vote percentages. We will retain blank, null and undecided categories, rather than silently allocating them to candidates.':'Cenários de primeiro e segundo turnos ficam separados, assim como percentuais do total de entrevistados e de votos válidos. Brancos, nulos e indecisos serão preservados, sem alocação silenciosa aos candidatos.',
  'The fieldwork midpoint locates a poll in time. The model will also retain the fieldwork duration, sample design and mode. Published sampling margins are not a complete measure of total polling error.':'O ponto médio do campo situa a pesquisa no tempo. O modelo também preservará a duração do campo, desenho amostral e modalidade. A margem publicada não mede todo o erro de uma pesquisa.',
  'The first prototype’s trend lines are synthetic. No house-effect model, weighting scheme or statistical smoothing has been implemented.':'As tendências deste protótipo são sintéticas. Não há modelo de efeitos dos institutos, ponderação ou suavização estatística implementado.',
  'Demographic correction, where justified':'Correção demográfica, quando justificável',
  'More recent population figures do not automatically make a poll correctable. The target must match the survey’s universe: resident population, eligible voters, registered electorate or likely voters are different populations.':'Dados populacionais recentes não tornam uma pesquisa automaticamente corrigível. A referência deve corresponder ao universo: residentes, pessoas aptas a votar, eleitores registrados e prováveis votantes são populações diferentes.',
  'The proposed benchmark sources are':'As fontes de referência propostas são','IBGE’s PNAD Contínua':'PNAD Contínua do IBGE','and, when the target is the registered electorate,':'e, para o eleitorado registrado, as','TSE electorate statistics':'estatísticas de eleitorado do TSE',
  'Published cross-tabs:':'Tabelas por subgrupos:','complete subgroup vote shares and compatible subgroup weights may support a one-variable standardization or a sensitivity analysis.':'percentuais completos por subgrupo e pesos compatíveis podem permitir padronização de uma variável ou análise de sensibilidade.',
  'Marginals alone:':'Apenas marginais:','age, education and region tables do not reveal how those characteristics overlap. Combining them is not equivalent to correcting the individual respondents.':'tabelas de idade, escolaridade e região não revelam como essas características se sobrepõem. Combiná-las não equivale a corrigir os entrevistados individualmente.',
  'Microdata:':'Microdados:','joint demographic adjustment requires respondent-level information or sufficiently detailed joint cells, original weights and design information.':'o ajuste demográfico conjunto exige informações individuais ou células conjuntas detalhadas, pesos originais e dados sobre o desenho da pesquisa.',
  'Any correction will disclose the available inputs, assumptions, weight limits and uncertainty. When evidence is insufficient, the result stays uncorrected and the limitation stays visible.':'Toda correção explicitará insumos, hipóteses, limites dos pesos e incerteza. Sem evidência suficiente, o resultado ficará sem correção e a limitação será informada.',
  'The historical ranking will compare polls with certified outcomes at matched points in the election cycle. A poll months before an election should not be judged as though it were a final-week forecast.':'O ranking histórico comparará pesquisas com resultados oficiais em momentos equivalentes do ciclo eleitoral. Uma pesquisa meses antes da eleição não deve ser julgada como uma previsão da última semana.',
  'Each scorecard will separate absolute error, signed error, interval coverage and the number of comparable observations. Election, round, geographic scope and vote denominator must match. A small evidence base will not support a confident quality grade.':'Cada avaliação separará erro absoluto, erro com sinal, cobertura dos intervalos e número de observações comparáveis. Eleição, turno, abrangência e base percentual devem coincidir. Poucos dados não sustentam uma nota de qualidade confiável.',
  'Institute-specific tendencies—often called house effects—will be estimated with partial pooling. This allows shared information without assuming that one historical miss proves a permanent bias.':'Tendências específicas dos institutos — os efeitos de casa — serão estimadas com compartilhamento parcial de informação, sem presumir que um erro histórico prove um viés permanente.',
  'The distance-to-Observer view takes each institute’s latest raw published second-round result and compares it with the PNAD- and house-bias-corrected Observer estimate as of that same publication date, before any election-day or Monte Carlo projection. Both sides use the same candidate pairing and total-respondent denominator. The publication date is the comparison cutoff; fieldwork dates remain visible. Production comparisons must use only inputs available by that cutoff.':'A distância ao Observer compara o último resultado bruto publicado de cada instituto no segundo turno à estimativa do Observer corrigida por PNAD e viés na mesma data, antes de qualquer projeção eleitoral ou de Monte Carlo. Os dois lados usam o mesmo confronto e o total de entrevistados. A publicação define a data de corte; as datas de campo continuam visíveis. Só podem ser usados insumos disponíveis até esse corte.',
  'The current-distance ranking runs from smallest to largest absolute difference divided by the published margin of error. It also displays the signed percentage-point gap and the excess outside the margin. Missing margins or incompatible benchmarks are not ranked. This descriptive ratio is not a z-score or significance test: the benchmark is uncertain, and shared poll inputs can induce dependence. Historical errors remain a separate, largest-first ranking. Distance is disagreement, not proof that an institute is wrong. All institute names, corrected benchmarks and grades here are fictional.':'O ranking atual ordena da menor à maior diferença absoluta dividida pela margem publicada. Também mostra a diferença com sinal e o excesso além da margem. Sem margem ou referência compatível, não há classificação. Essa razão descritiva não é um escore-z nem um teste de significância: a referência é incerta e insumos compartilhados podem gerar dependência. Erros históricos têm ranking separado, do maior para o menor. Distância é divergência, não prova de erro. Nomes, referências corrigidas e notas são fictícios.',
  'The proposed system combines a latent opinion trend with polling error, mode and institute effects, then adds election-day uncertainty. First-round vote shares must remain non-negative and sum to the defined total.':'O sistema proposto combina uma tendência latente de opinião com erros de pesquisa e efeitos de modalidade e instituto, acrescentando incerteza até a eleição. Percentuais de primeiro turno devem ser não negativos e somar o total definido.',
  'Turnout and undecided-voter behaviour will be treated as uncertain scenarios, not fixed redistributions. Second-round modelling on this site is restricted to the two leading first-round candidates, as specified in the product brief.':'Comparecimento e comportamento dos indecisos serão cenários incertos, não redistribuições fixas. O segundo turno se limita aos dois líderes do primeiro turno, conforme a proposta do site.',
  'Monte Carlo simulations will draw shared election-wide errors, correlated institute or mode errors and candidate-level variation. Polls are not independent merely because they come from different institutes.':'Simulações de Monte Carlo incluirão erros comuns à eleição, erros correlacionados por instituto ou modalidade e variação por candidato. Pesquisas não são independentes só por serem de institutos diferentes.',
  'Expected vote share and probability of victory are distinct outputs. The landing-page prototype shows illustrative second-round election-day vote shares, a projected winner at the expected value, and mock 95% intervals. These are design fixtures, not calibrated predictions.':'Percentual esperado e probabilidade de vitória são resultados distintos. A página inicial mostra votos ilustrativos de segundo turno, um vencedor pelo valor esperado e intervalos fictícios de 95%. São exemplos de design, não previsões calibradas.',
  'Showing uncertainty honestly':'Apresentação transparente da incerteza',
  'Validation will replay historical elections using only the information available at each simulated cutoff. Rolling-origin backtests will prevent later data from leaking into earlier forecasts.':'A validação reproduzirá eleições históricas apenas com informações disponíveis em cada corte simulado. Testes com cortes sucessivos impedirão que dados posteriores contaminem previsões anteriores.',
  'We will examine interval coverage, absolute errors, calibration and sensitivity to uncertain assumptions. A polished line or a large simulation count cannot compensate for a misspecified model.':'Serão avaliados cobertura dos intervalos, erros absolutos, calibração e sensibilidade às hipóteses. Um gráfico bonito ou muitas simulações não compensam um modelo mal especificado.',
  'Final intervals must include relevant sampling, non-sampling, demographic, turnout and future-change uncertainty. The prototype’s shaded bands are design placeholders and have no statistical coverage claim.':'Os intervalos finais devem incluir incertezas amostrais, não amostrais, demográficas, de comparecimento e de mudanças futuras. As faixas do protótipo são ilustrativas e não têm cobertura estatística garantida.',
  'Kalshi and Polymarket remain a separate view of market prices. They will not be quietly averaged into the polling estimate or used as independent confirmation of it.':'Kalshi e Polymarket permanecem uma visão separada dos preços de mercado. Não serão incorporados silenciosamente à média de pesquisas nem usados como confirmação independente dela.',
  'Every snapshot retains provider, contract, observation time, retrieval time and available resolution. Missing prices stay missing, and long gaps interrupt the line. Different market definitions and settlement rules limit direct comparisons.':'Cada arquivo preserva fornecedor, contrato, horário da observação, horário da coleta e resolução disponível. Preços ausentes permanecem ausentes; lacunas longas interrompem a linha. Definições e regras distintas limitam comparações diretas.',
  'Each published model run will record its input snapshot, source hashes, transformations, model version, parameters, random seed, simulation count and validation report. Corrections will have an explicit change log.':'Cada execução publicada registrará os insumos, hashes das fontes, transformações, versão do modelo, parâmetros, semente aleatória, número de simulações e relatório de validação. Correções terão histórico explícito.',
  'The proposed publishing chain separates raw evidence, cleaned data, model output and presentation. The current local prototype does not alter the Hostinger jobs, repository sync or production data.':'A publicação proposta separa evidência bruta, dados tratados, resultados do modelo e apresentação. Este protótipo local não altera rotinas da Hostinger, sincronização do repositório ou dados de produção.',
  'Inspect the prototype database':'Consulte a base do protótipo','The page could not load.':'Não foi possível carregar a página.','Please reload the local prototype. Its production counterpart is unaffected.':'Recarregue o protótipo local. O site em produção não foi afetado.','Reload':'Recarregar','Reload page':'Recarregar página',
  'The other chart can still be used. Check the local data file and reload.':'O outro gráfico continua disponível. Verifique o arquivo local e recarregue.',
  'Illustrative institute series—not published poll results.':'Série fictícia por instituto — não representa pesquisas publicadas.',
  'All institutes · synthetic overview':'Todos os institutos · visão sintética geral'
};

const fragments=[
 [' expected valid votes',' de votos válidos esperados'],
 [' · synthetic series',' · séries sintéticas'],
 ['Expected valid-vote share','Percentual esperado de votos válidos'],['detail scale','escala detalhada'],['percentage points','pontos percentuais'],['0–60% scale','escala de 0–60%'],['Flávio minus Lula','Flávio menos Lula'],
 ['Institute ','Instituto '],['Candidate C','Candidato C'],['Candidate D','Candidato D'],['As of ','Em '],[' respondents',' entrevistados'],['Source: ','Fonte: '],[' data from the existing Observer snapshot.',' — dados do arquivo histórico do Observer.'],
 ['Snapshot cutoff: ','Data de corte: '],['Daily archive','Arquivo diário'],['Six-hour source history','Histórico da fonte a cada seis horas'],['Hourly source history','Histórico horário da fonte'],['UTC throughout','Todos os horários em UTC'],[' snapshot unavailable',' — arquivo indisponível'],[' archived contract prices',' — preços históricos de contratos'],[' period',' — período'],
 ['Illustrative runoff vote-share trend','Tendência ilustrativa de votos no segundo turno'],['Illustrative first-round leaders vote-share trends','Tendências ilustrativas dos líderes no primeiro turno'],['Illustrative other first-round candidates vote-share trends','Tendências ilustrativas dos demais candidatos'],['Illustrative runoff lead: ','Diferença ilustrativa no segundo turno: '],[' in percentage points',' em pontos percentuais'],
 ['. Use left and right arrow keys to inspect observations.','. Use as setas esquerda e direita para consultar as observações.'],['. Exact values available in the chart readout and data table.','. Valores exatos disponíveis na leitura do gráfico e na tabela.'],['Mock grade ','Nota fictícia '],
 ['Illustrative second-round election semicircle. Lula on the left: ','Semicírculo eleitoral ilustrativo de segundo turno. Lula à esquerda: '],['Flávio Bolsonaro on the right: ','Flávio Bolsonaro à direita: '],['95% interval ','intervalo de 95% '],[' to ',' a '],['The outer bracket marks uncertainty in the shared boundary. Both intervals cross 50%.','O arco externo mostra a incerteza na divisão entre os candidatos. Ambos os intervalos cruzam 50%.'],
 ['observation timestamps.','horários de observação.'],['Latest ','Últimos '],['shown; CSV includes the entire selection.','exibidos; o CSV inclui toda a seleção.'],['Blank cells are unavailable, not zero.','Células vazias são valores indisponíveis, não zero.'],['Timestamp (UTC)','Data e hora (UTC)'],
 ['illustrative first-round records · Published percentages, total respondents · Fictional institutes','registros ilustrativos de primeiro turno · Percentuais publicados, total de entrevistados · Institutos fictícios'],['illustrative second-round records · Published percentages, total respondents · Fictional institutes','registros ilustrativos de segundo turno · Percentuais publicados, total de entrevistados · Institutos fictícios'],['Individual first-round polls. All records are fictional.','Pesquisas individuais de primeiro turno. Todos os registros são fictícios.'],['Individual second-round polls. All records are fictional.','Pesquisas individuais de segundo turno. Todos os registros são fictícios.']
].sort((a,b)=>b[0].length-a[0].length);
export function translate(value,lang=language){
  if(lang!=='pt')return value;
  const trimmed=value.trim();let translated=translations[trimmed];
  if(translated===undefined){translated=trimmed;for(const [en,pt] of fragments)translated=translated.split(en).join(pt);}
  translated=translated.replace(/(\d)\.(\d{1,2})(?=%|×|\s*p\.p\.|$)/g,'$1,$2');
  return value.slice(0,value.indexOf(trimmed))+translated+value.slice(value.indexOf(trimmed)+trimmed.length);
}

export function localizeDOM(root=document.body){
  if(!root)return;
  const elements=root.nodeType===1?[root,...root.querySelectorAll('*')]:[];
  // Keep control values canonical even when their visible option labels are translated.
  for(const e of elements){
    if(e.tagName==='OPTION'&&!e.hasAttribute('value'))e.setAttribute('value',e.textContent);
    if(e.tagName==='A'&&!e.dataset.language){const href=e.getAttribute('href');if(language==='pt'&&href&&/^(index|first-round|second-round|bet-markets|adjusted-results|offenders|methodology|database)\.html/.test(href))e.setAttribute('href','pt/'+href);}
    if(language==='pt')for(const attr of ['aria-label','placeholder','title'])if(e.hasAttribute(attr)){const old=e.getAttribute(attr),next=translate(old);if(old!==next)e.setAttribute(attr,next);}
  }
  if(language!=='pt')return;
  const nodes=[];if(root.nodeType===3)nodes.push(root);else{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode())nodes.push(walker.currentNode);}
  for(const node of nodes){if(node.parentElement?.closest('script,style,[data-language]'))continue;const next=translate(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next;}
}

export function observeTranslations(){
  localizeDOM();
  const observer=new MutationObserver(records=>{
    observer.disconnect();
    const roots=new Set();for(const r of records){if(r.type==='characterData')roots.add(r.target);else for(const n of r.addedNodes)roots.add(n);}
    roots.forEach(localizeDOM);observer.observe(document.body,{childList:true,subtree:true,characterData:true});
  });
  observer.observe(document.body,{childList:true,subtree:true,characterData:true});
}
