import {instituteRankings} from './data/institute-rankings.js';

const E=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(value,pt=false,digits=2)=>new Intl.NumberFormat(pt?'pt-BR':'en-GB',{minimumFractionDigits:digits,maximumFractionDigits:digits,signDisplay:'always'}).format(value);
const valueFmt=(value,pt=false)=>new Intl.NumberFormat(pt?'pt-BR':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);

function historicalRankingChart(lang){
  const pt=lang==='pt',L=(a,b)=>pt?b:a,rows=[...instituteRankings.historical_errors].sort((a,b)=>b.mean_absolute_margin_error_pp-a.mean_absolute_margin_error_pp);
  const max=Math.max(...rows.map(row=>row.mean_absolute_margin_error_pp));
  const bars=rows.map(row=>`<div class="historical-error-row"><span class="historical-error-label">${E(row.institute)}</span><span class="historical-error-track"><i style="--bar:${row.mean_absolute_margin_error_pp/max*100}%"><span class="screen-reader">${E(row.institute)} · ${valueFmt(row.mean_absolute_margin_error_pp,pt)} ${L('percentage points','pontos percentuais')} · ${row.event_rounds} ${L('rounds','turnos')}</span></i></span><strong>${valueFmt(row.mean_absolute_margin_error_pp,pt)} pp</strong></div>`).join('');
  return `<figure class="historical-error-figure"><div class="historical-error-chart" role="img" aria-label="${L('Mean absolute historical margin error by institute, ranked largest to smallest','Erro absoluto médio histórico da margem por instituto, do maior para o menor')}">${bars}</div><figcaption>${L('Mean absolute error in the Lula–opponent margin, percentage points. Larger bars indicate a larger historical miss.','Erro absoluto médio na margem Lula–adversário, em pontos percentuais. Barras maiores indicam erro histórico maior.')}</figcaption></figure>`;
}

function historicalTable(lang){
  const pt=lang==='pt',L=(a,b)=>pt?b:a;
  const rows=instituteRankings.historical_errors.map((item,index)=>`<tr><td>${index+1}</td><th scope="row">${E(item.institute)}</th><td class="num">${valueFmt(item.mean_absolute_margin_error_pp,pt)} pp</td><td class="num">${item.event_rounds}</td></tr>`).join('');
  return `<div class="table-scroll"><table><caption class="table-caption">${L('The chart and table use the same total-error measure and descending order.','O gráfico e a tabela usam a mesma medida de erro total e a mesma ordem decrescente.')}</caption><thead><tr><th>#</th><th>${L('Institute','Instituto')}</th><th class="num">${L('Mean absolute margin error','Erro absoluto médio da margem')}</th><th class="num">${L('Election rounds','Turnos eleitorais')}</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}

function currentCorrectionsTable(lang){
  const pt=lang==='pt',L=(a,b)=>pt?b:a;
  const rows=instituteRankings.current_corrections.map((item,index)=>`<tr><td>${index+1}</td><th scope="row">${E(item.institute)}<small class="table-muted">${item.published}</small></th><td class="num">${fmt(item.raw_margin_flavio_minus_lula,pt)} pp</td><td class="num">${item.pnad_adjustment_pp==null?'—':fmt(item.pnad_adjustment_pp,pt)+' pp'}</td><td class="num">${fmt(item.residual_correction_pp,pt)} pp</td><td class="num">${fmt(item.total_available_correction_pp,pt)} pp${item.total_is_complete?'':`<small class="table-muted">${L('partial','parcial')}</small>`}</td></tr>`).join('');
  return `<section id="current-corrections"><h2>${L('Current correction ledger','Registro das correções atuais')}</h2><p>${L('This separate table preserves the current research ledger requested for audit: raw margin, supported PNAD contribution, residual standardization and available total. It is not the historical error ranking above. A dash means unavailable, not zero.','Esta tabela separada preserva o registro atual solicitado para auditoria: margem bruta, contribuição PNAD sustentada, padronização residual e total disponível. Ela não é o ranking de erro histórico acima. Um traço significa indisponível, não zero.')}</p><div class="table-scroll"><table><caption class="table-caption">${L('Flávio-minus-Lula margin, percentage points','Margem Flávio menos Lula, pontos percentuais')}</caption><thead><tr><th>#</th><th>${L('Institute / latest poll','Instituto / última pesquisa')}</th><th class="num">${L('Raw','Bruta')}</th><th class="num">PNAD</th><th class="num">${L('Residual','Resíduo')}</th><th class="num">${L('Available total','Total disponível')}</th></tr></thead><tbody>${rows}</tbody></table></div><p class="method-note">${L('Only Datafolha currently has a complete total because only its archived public tables support the demographic reconstruction. Other totals are partial and must not be read as fully adjusted institute estimates.','Apenas o Datafolha tem hoje total completo porque somente suas tabelas públicas arquivadas sustentam a reconstrução demográfica. Os demais totais são parciais e não devem ser lidos como estimativas plenamente ajustadas dos institutos.')}</p></section>`;
}

export function offendersHTML(lang='en'){
  const pt=lang==='pt',L=(a,b)=>pt?b:a,methodology=`${pt?'pt/':''}methodology.html#historical-offenders`;
  return `<section class="page-intro"><div><h1>${L('Where the polls missed.','Onde as pesquisas erraram.')}</h1><p>${L('A historical ranking based on total error in the candidate margin, ordered from the largest miss to the smallest.','Um ranking histórico baseado no erro total da margem entre candidatos, ordenado do maior erro para o menor.')}</p></div></section><article class="offenders-article"><section id="historical-ranking"><h2>${L('Historical polling error by institute','Erro histórico das pesquisas por instituto')}</h2><p>${L('For each certified election round, the calculation selects the latest eligible total-respondent poll published within 14 days of the vote, measures the absolute difference between its Lula–opponent margin and the official result, then averages those absolute errors by institute. The chart shows only that total historical error—no PNAD, residual or margin-of-error breakdown.','Para cada turno certificado, o cálculo seleciona a última pesquisa elegível sobre o total de entrevistados publicada até 14 dias antes da votação, mede a diferença absoluta entre sua margem Lula–adversário e o resultado oficial e calcula a média desses erros absolutos por instituto. O gráfico mostra apenas esse erro histórico total — sem decomposição por PNAD, resíduo ou margem de erro.')}</p>${historicalRankingChart(lang)}${historicalTable(lang)}<p class="method-note">${L('The number of comparable rounds is small and differs by institute. This is an evidence summary, not a permanent quality grade or a claim of intentional bias.','O número de turnos comparáveis é pequeno e varia por instituto. Este é um resumo de evidências, não uma nota permanente de qualidade nem uma alegação de viés intencional.')}</p><p><a class="text-link" href="${methodology}">${L('Read how the offenders ranking is calculated','Leia como o ranking de erros é calculado')}</a></p></section>${currentCorrectionsTable(lang)}<section id="residual-status"><h2>${L('How to read the residual','Como ler o resíduo')}</h2><p>${L('The residual model estimates systematic margin error not explained by the available demographic correction. It is stored separately from PNAD and used only as a research standardization. Historical demographic inputs could not be replayed consistently, so the present residual may still contain demographic effects.','O modelo residual estima o erro sistemático de margem não explicado pela correção demográfica disponível. Ele é armazenado separadamente da PNAD e usado apenas como padronização de pesquisa. Os insumos demográficos históricos não puderam ser reproduzidos de modo consistente; portanto, o resíduo atual ainda pode conter efeitos demográficos.')}</p></section></article>`;
}
